name: Update Trending

on:
    schedule:
        - cron: "30 15 * * *" # 日次: 日本時間 24:30 = UTC 15:30
        - cron: "30 15 * * 1" # 週次: 毎週月曜 日本時間 24:30
        - cron: "30 15 1 * *" # 月次: 毎月1日 日本時間 24:30
        - cron: "30 15 1 1 *" # 年次: 毎年1月1日 日本時間 24:30
    workflow_dispatch: # 手動実行も可能

permissions:
    contents: write

jobs:
    daily:
        if: github.event.schedule == '30 15 * * *' || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        timeout-minutes: 100
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - run: pip install requests beautifulsoup4 feedparser
            - name: Run daily update
              run: python scripts/update_readme.py
            - run: |
                  git config --local user.email "so_kaicyo@icloud.com"
                  git config --local user.name "immunity39"
                  git add README.md
                  git commit -m "Daily update"
                  git push

    weekly:
        if: github.event.schedule == '30 15 * * 1'
        runs-on: ubuntu-latest
        timeout-minutes: 100
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - run: pip install requests beautifulsoup4 feedparser
            - name: Run weekly update
              run: python scripts/update_weekly.py
            - run: |
                  git config --local user.email "so_kaicyo@icloud.com"
                  git config --local user.name "immunity39"
                  git add docs/weekly/
                  git commit -m "Weekly update"
                  git push

    monthly:
        if: github.event.schedule == '30 15 1 * *'
        runs-on: ubuntu-latest
        timeout-minutes: 100
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - run: pip install requests beautifulsoup4 feedparser
            - name: Run monthly update
              run: python scripts/update_monthly.py
            - run: |
                  git config --local user.email "so_kaicyo@icloud.com"
                  git config --local user.name "immunity39"
                  git add docs/monthly/
                  git commit -m "Monthly update"
                  git push

    yearly:
        if: github.event.schedule == '30 15 1 1 *'
        runs-on: ubuntu-latest
        timeout-minutes: 100
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - run: pip install requests beautifulsoup4 feedparser
            - name: Run yearly update
              run: python scripts/update_yearly.py
            - run: |
                  git config --local user.email "so_kaicyo@icloud.com"
                  git config --local user.name "immunity39"
                  git add docs/yearly/
                  git commit -m "Yearly update"
                  git push
