name: Update Trending

on:
  schedule:
    - cron: "30 15 * * *"  # 日次: 日本時間 24:30 = UTC 15:30
    - cron: "30 15 * * 1"  # 週次: 毎週月曜 日本時間 24:30
    - cron: "30 15 1 * *"  # 月次: 毎月1日 日本時間 24:30
    - cron: "30 15 1 1 *"  # 年次: 毎年1月1日 日本時間 24:30
  workflow_dispatch:
    inputs:
      target:
        description: 'Select update target'
        required: false
        type: choice
        options:
          - daily
          - weekly
          - monthly
          - yearly
          - all
        default: 'daily'

permissions:
  contents: write

jobs:
  daily:
    if: >
      github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.target == 'daily' ||
       github.event.inputs.target == 'all' ||
       github.event.inputs.target == '' ) ||
      github.event.schedule == '30 15 * * *'
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install requests beautifulsoup4 feedparser
      - name: Run daily update
        run: python scripts/update_readme.py
      - run: |
          git config --local user.email "so_kaicyo@icloud.com"
          git config --local user.name "immunity39"
          git add README.md
          git commit -m "Daily update" || echo "No changes"
          git push

  weekly:
    if: >
      (github.event_name == 'workflow_dispatch' &&
       (github.event.inputs.target == 'weekly' || github.event.inputs.target == 'all')) ||
      github.event.schedule == '30 15 * * 1'
    needs: [daily]
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install requests beautifulsoup4 feedparser
      - name: Run weekly update
        run: python scripts/weekly.py
      - run: |
          git config --local user.email "so_kaicyo@icloud.com"
          git config --local user.name "immunity39"
          git add docs/weekly/
          git commit -m "Weekly update" || echo "No changes"
          git push

  monthly:
    if: >
      (github.event_name == 'workflow_dispatch' &&
       (github.event.inputs.target == 'monthly' || github.event.inputs.target == 'all')) ||
      github.event.schedule == '30 15 1 * *'
    needs: [weekly]
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install requests beautifulsoup4 feedparser
      - name: Run monthly update
        run: python scripts/monthly.py
      - run: |
          git config --local user.email "so_kaicyo@icloud.com"
          git config --local user.name "immunity39"
          git add docs/monthly/
          git commit -m "Monthly update" || echo "No changes"
          git push

  yearly:
    if: >
      (github.event_name == 'workflow_dispatch' &&
       (github.event.inputs.target == 'yearly' || github.event.inputs.target == 'all')) ||
      github.event.schedule == '30 15 1 1 *'
    needs: [monthly]
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install requests beautifulsoup4 feedparser
      - name: Run yearly update
        run: python scripts/yearly.py
      - run: |
          git config --local user.email "so_kaicyo@icloud.com"
          git config --local user.name "immunity39"
          git add docs/yearly/
          git commit -m "Yearly update" || echo "No changes"
          git push