name: Update Trending Articles

on:
  schedule:
    - cron: "0 15 * * *"  # 日本時間24:00に実行 (UTC換算)
  workflow_dispatch:       # 手動実行

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests feedparser beautifulsoup4 lxml
      - name: Run update script
        run: python scripts/update_readme.py
      - name: Commit changes
        run: |
          git config user.name "immunity39"
          git config user.email "so_kaicyo@icloud.com"
          git add README.md
          git commit -m "Update README with daily top1" || echo "No changes"
          git push
